services:
  - type: web
    name: histree-api
    env: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
